# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: hello.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import hello_pb2 as hello__pb2


class HelloService(Protocol):
    async def say_hello(self, request: hello__pb2.HelloRequest, ctx: RequestContext) -> hello__pb2.HelloResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class HelloServiceASGIApplication(ConnectASGIApplication[HelloService]):
    def __init__(self, service: HelloService | AsyncGenerator[HelloService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/example.v1.HelloService/SayHello": Endpoint.unary(
                    method=MethodInfo(
                        name="SayHello",
                        service_name="example.v1.HelloService",
                        input=hello__pb2.HelloRequest,
                        output=hello__pb2.HelloResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.say_hello,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/example.v1.HelloService"


class HelloServiceClient(ConnectClient):
    async def say_hello(
        self,
        request: hello__pb2.HelloRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> hello__pb2.HelloResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SayHello",
                service_name="example.v1.HelloService",
                input=hello__pb2.HelloRequest,
                output=hello__pb2.HelloResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class HelloServiceSync(Protocol):
    def say_hello(self, request: hello__pb2.HelloRequest, ctx: RequestContext) -> hello__pb2.HelloResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class HelloServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: HelloServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/example.v1.HelloService/SayHello": EndpointSync.unary(
                    method=MethodInfo(
                        name="SayHello",
                        service_name="example.v1.HelloService",
                        input=hello__pb2.HelloRequest,
                        output=hello__pb2.HelloResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.say_hello,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/example.v1.HelloService"


class HelloServiceClientSync(ConnectClientSync):
    def say_hello(
        self,
        request: hello__pb2.HelloRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> hello__pb2.HelloResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SayHello",
                service_name="example.v1.HelloService",
                input=hello__pb2.HelloRequest,
                output=hello__pb2.HelloResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
